### ISSUE TITLE
Add environment variables

### ISSUE THREAD

**Issue by nvick** [hintmedia/railsdock#14]
Add environment variables for `REDIS_URL` or `MEMCACHED_HOST` to `x-ruby`

for example if redis is chosen:
```yaml
 x-ruby:  &ruby-base
   build: 
     ....other code....
   environment:
     REDIS_URL=redis://redis:6379/0
```
